"""indexing

Revision ID: 0664df66f604
Revises: 7940fa470349
Create Date: 2024-12-25 03:07:54.357694

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0664df66f604'
down_revision: Union[str, None] = '7940fa470349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    # ### end Alembic commands ###
