"""assosiating a list of books to user

Revision ID: 0fb7d9d2fcd6
Revises: c97f085a1d93
Create Date: 2024-12-26 17:08:00.998336

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb7d9d2fcd6'
down_revision: Union[str, None] = 'c97f085a1d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
