"""assosiating a list of books to user

Revision ID: 221cf4ac610a
Revises: caa1c8250ffb
Create Date: 2024-12-26 17:25:30.066074

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221cf4ac610a'
down_revision: Union[str, None] = 'caa1c8250ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
