"""final ig

Revision ID: 2732bafbd075
Revises: 512837513639
Create Date: 2024-12-26 18:36:27.761058

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2732bafbd075'
down_revision: Union[str, None] = '512837513639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
