"""assosiating a list of books to user

Revision ID: 28029c6de8af
Revises: 0fb7d9d2fcd6
Create Date: 2024-12-26 17:09:27.965239

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28029c6de8af'
down_revision: Union[str, None] = '0fb7d9d2fcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
