"""add role to users table

Revision ID: 74a206c6c6c3
Revises: 0664df66f604
Create Date: 2024-12-25 17:30:44.514200

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a206c6c6c3'
down_revision: Union[str, None] = '0664df66f604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'role')
    # ### end Alembic commands ###
